/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState } from "react";

import { type Language, LANGUAGES } from "../config/languages";

const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "Language": "Language",
    "Dashboard": "Dashboard",
    "Student": "Student",
    "Parents": "Parents",
    "Teacher": "Teacher",
    "User": "User",
    "Attendance": "Attendance",
    "Student Attendance": "Student Attendance",
    "Teacher Attendance": "Teacher Attendance",
    "User Attendance": "User Attendance",
    "Message": "Message",
    "Media": "Media",
    "Leave Apply": "Leave Apply",
    "Announcement": "Announcement",
    "Notice": "Notice",
    "Event": "Event",
    "Holiday": "Holiday",
    "Visitor Information": "Visitor Information",
    "Report": "Report",
    "Library Books Report": "Library Books Report",
    "Library Card Report": "Library Card Report",
    "Library Book Issue Report": "Library Book Issue Report",
    "Member": "Member",
    "Books": "Books",
    "Issue": "Issue",
    "Welcome to the Librarian Dashboard!": "Welcome to the Librarian Dashboard!",
    "Welcome to the Receptionist Dashboard!": "Welcome to the Receptionist Dashboard!",
    "Welcome to the Admin Dashboard!": "Welcome to the Admin Dashboard!",
    "Welcome to the Dashboard!": "Welcome to the Dashboard!",
    "Profile": "Profile",
    "Password": "Password",
    "Log out": "Log out",
    "Username": "Username",
    "Email": "Email",
    "Phone": "Phone",
    "Address": "Address",
    "Status": "Status",
    "Action": "Action",
    "Active": "Active",
    "Sun": "Sun", "Mon": "Mon", "Tue": "Tue", "Wed": "Wed", "Thu": "Thu", "Fri": "Fri", "Sat": "Sat",
    "January": "January", "February": "February", "March": "March", "April": "April", "May": "May", "June": "June",
    "July": "July", "August": "August", "September": "September", "October": "October", "November": "November", "December": "December",
    "today": "today", "month": "month", "week": "week", "day": "day", "list": "list",

    // Notice items details
    "Library closed": "Library closed",
    "The library will be closed tomorrow for system maintenance.": "The library will be closed tomorrow for system maintenance.",
    "Farewell Ceremony": "Farewell Ceremony",
    "The most of the words adopted by the Russian langu..": "The most of the words adopted by the Russian langu..",
    "Second Semester Exam": "Second Semester Exam",
    "Dedicated athlete, an amateur player, or a sport g..": "Dedicated athlete, an amateur player, or a sport g..",
    "First Semester Exam": "First Semester Exam",
    "If you are a dedicated athlete, an amateur player,..": "If you are a dedicated athlete, an amateur player,..",
    "Annual Sports Day": "Annual Sports Day",
    "You surely are familiar with the sport language. A..": "You surely are familiar with the sport language. A..",
    "Teachers Reunion": "Teachers Reunion",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "An amateur player, or a sport geek, than you surely are familiar with ..",
    
    // Login & profile specific
    "librarian": "librarian",
    "receptionist": "receptionist",
    "Librarian": "Librarian",
    "Receptionist": "Receptionist",
    "Admin": "Admin",
    "Teacher Role": "Teacher",
    "Student Role": "Student",
    "Parent Role": "Parent",
    "Accountant Role": "Accountant",
    "Fee Collection": "Fee Collection",
    "My Child": "My Child",
    "Child Attendance": "Child Attendance",
    "My Attendance": "My Attendance",
    "Subject": "Subject",
    "is successfully logged in. This section is currently under development.": "is successfully logged in. This section is currently under development.",
    "All Students": "All Students",
    "Copy": "Copy",
    "Excel": "Excel",
    "CSV": "CSV",
    "PDF": "PDF",
    "Select Class": "Select Class",
    "Photo": "Photo",
    "Roll": "Roll",
    "No data available in table": "No data available in table",
    "Showing": "Showing",
    "to": "to",
    "of": "of",
    "entries": "entries",
    "Previous": "Previous",
    "Next": "Next",
    "Arabic": "Arabic",
    "Bengali": "Bengali",
    "Chinese": "Chinese",
    "English": "English",
    "French": "French",
    "German": "German",
    "All Teachers": "All Teachers",
    "All Parents": "All Parents",
    "All Users": "All Users",
    "Designation": "Designation",
    "Moderator": "Moderator",
    "Attendance Date": "Attendance Date",
    "Present": "Present",
    "Absent": "Absent",
    "Late": "Late",
    "Father's Name": "Father's Name",
    "Mother's Name": "Mother's Name",
    "Father's Profession": "Father's Profession",
    "Mother's Profession": "Mother's Profession",
    "Class": "Class",
    "Section": "Section",
    "Department": "Department",
    "Join Date": "Join Date",
    "Role": "Role",
    "Instructor": "Instructor",
    "Female": "Female",
    "Compose": "Compose",
    "Folders": "Folders",
    "Drafts": "Drafts",
    "Sent": "Sent",
    "Trash": "Trash",
    "records per page": "records per page",
    "Add a leave application": "Add a leave application",
    "Application To": "Application To",
    "Days": "Days",
    "Attachment": "Attachment",
    "Schedule": "Schedule",
    "Approved": "Approved",
    "Pending": "Pending",
    "Drag and drop files here or click to upload": "Drag and drop files here or click to upload",
    "Support images, videos, and folders": "Support images, videos, and folders",
    "Search Media": "Search Media",
    "Filter by name...": "Filter by name...",
    "New Folder / File": "New Folder / File",
    "No media items found": "No media items found",
    "items": "items",
    "Visitor List": "Visitor List",
    "Visitor Add": "Visitor Add",
    "Visitor ID": "Visitor ID",
    "To meet": "To meet",
    "Add Visitor Information": "Add Visitor Information",
    "Visitor Details": "Visitor Details",
    "in": "In",
    "out": "Out",
    "Name is required": "Name is required"
  },
  ar: {
    "Language": "اللغة",
    "Dashboard": "لوحة القيادة",
    "Student": "طالب",
    "Parents": "أولياء الأمور",
    "Teacher": "معلم",
    "User": "مستخدم",
    "Attendance": "الحضور",
    "Student Attendance": "حضور الطلاب",
    "Teacher Attendance": "حضور المعلمين",
    "User Attendance": "حضور المستخدمين",
    "Message": "رسالة",
    "Media": "وسائط",
    "Leave Apply": "طلب إجازة",
    "Announcement": "إعلان",
    "Notice": "تنويه",
    "Event": "حدث",
    "Holiday": "عطلة",
    "Visitor Information": "معلومات الزائر",
    "Report": "التقرير",
    "Library Books Report": "تقرير كتب المكتبة",
    "Library Card Report": "تقرير بطاقات المكتبة",
    "Library Book Issue Report": "تقرير إعارة كتب المكتبة",
    "Member": "عضو",
    "Books": "كتب",
    "Issue": "إعارة",
    "Welcome to the Librarian Dashboard!": "مرحبًا بك في لوحة تحكم أمين المكتبة!",
    "Welcome to the Receptionist Dashboard!": "مرحبًا بك في لوحة تحكم موظف الاستقبال!",
    "Welcome to the Admin Dashboard!": "مرحبًا بك في لوحة تحكم المسؤول!",
    "Welcome to the Dashboard!": "مرحبًا بك في لوحة القيادة!",
    "Profile": "الملف الشخصي",
    "Password": "كلمة المرور",
    "Log out": "تسجيل الخروج",
    "Username": "اسم المستخدم",
    "Email": "البريد الإلكتروني",
    "Phone": "الهاتف",
    "Address": "العنوان",
    "Status": "الحالة",
    "Action": "الإجراء",
    "Active": "نشط",
    "Sun": "الأحد", "Mon": "الاثنين", "Tue": "الثلاثاء", "Wed": "الأربعاء", "Thu": "الخميس", "Fri": "الجمعة", "Sat": "السبت",
    "January": "يناير", "February": "فبراير", "March": "مارس", "April": "أبريل", "May": "مايو", "June": "يونيو",
    "July": "يوليو", "August": "أغسطس", "September": "سبتمبر", "October": "أكتوبر", "November": "نوفمبر", "December": "ديسمبر",
    "today": "اليوم", "month": "الشهر", "week": "الأسبوع", "day": "اليوم", "list": "القائمة",

    "Library closed": "المكتبة مغلقة",
    "The library will be closed tomorrow for system maintenance.": "ستغلق المكتبة غدًا لأعمال الصيانة للنظام.",
    "Farewell Ceremony": "حفل الوداع",
    "The most of the words adopted by the Russian langu..": "معظم الكلمات التي اعتمدتها اللغة الروسية..",
    "Second Semester Exam": "امتحان الفصل الدراسي الثاني",
    "Dedicated athlete, an amateur player, or a sport g..": "رياضي متفانٍ، أو لاعب هاوٍ، أو محب للرياضة..",
    "First Semester Exam": "امتحان الفصل الدراسي الأول",
    "If you are a dedicated athlete, an amateur player,..": "إذا كنت رياضيًا متفانيًا، أو لاعبًا هاوٍ،..",
    "Annual Sports Day": "اليوم الرياضي السنوي",
    "You surely are familiar with the sport language. A..": "أنت بالتأكيد على دراية بلغة الرياضة. أ..",
    "Teachers Reunion": "لم شمل المعلمين",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "لاعب هاوٍ، أو مهووس بالرياضة، فأنت بالتأكيد على دراية بـ..",
    
    "librarian": "أمين المكتبة",
    "receptionist": "موظف استقبال",
    "Librarian": "أمين المكتبة",
    "Receptionist": "موظف الاستقبال",
    "Admin": "مسؤول",
    "Teacher Role": "معلم",
    "Student Role": "طالب",
    "Parent Role": "ولي أمر",
    "Accountant Role": "محاسب",
    "Fee Collection": "جمع الرسوم",
    "My Child": "طفلي",
    "Child Attendance": "حضور الطفل",
    "My Attendance": "حضوري",
    "Subject": "المادة",
    "is successfully logged in. This section is currently under development.": "تم تسجيل دخوله بنجاح. هذا القسم قيد التطوير حاليًا.",
    "All Students": "جميع الطلاب",
    "Copy": "نسخ",
    "Excel": "إكسل",
    "CSV": "CSV",
    "PDF": "بي دي إف",
    "Select Class": "اختر الصف",
    "Photo": "الصورة",
    "Roll": "رقم الجلوس",
    "No data available in table": "لا توجد بيانات متاحة في الجدول",
    "Showing": "عرض",
    "to": "إلى",
    "of": "من",
    "entries": "المدخلات",
    "Previous": "السابق",
    "Next": "التالي",
    "Arabic": "العربية",
    "Bengali": "البنغالية",
    "Chinese": "الصينية",
    "English": "الإنجليزية",
    "French": "الفرنسية",
    "German": "الألمانية",
    "All Teachers": "جميع المعلمين",
    "All Parents": "جميع أولياء الأمور",
    "All Users": "جميع المستخدمين",
    "Designation": "المسمى الوظيفي",
    "Moderator": "المشرف",
    "Attendance Date": "تاريخ الحضور",
    "Present": "حاضر",
    "Absent": "غائب",
    "Late": "متأخر",
    "Father's Name": "اسم الأب",
    "Mother's Name": "اسم الأم",
    "Father's Profession": "مهنة الأب",
    "Mother's Profession": "معنة الأم",
    "Class": "الصف",
    "Section": "القسم",
    "Department": "القسم الدراسي",
    "Join Date": "تاريخ الانضمام",
    "Role": "الدور",
    "Instructor": "معلم",
    "Female": "أنثى",
    "Compose": "إنشاء",
    "Folders": "مجلدات",
    "Drafts": "مسودات",
    "Sent": "أرسلت",
    "Trash": "سلة المهملات",
    "records per page": "سجلات لكل صفحة",
    "Add a leave application": "إضافة طلب إجازة",
    "Application To": "تقديم الطلب إلى",
    "Days": "أيام",
    "Attachment": "مرفق",
    "Schedule": "الجدول الزمني",
    "Approved": "مقبول",
    "Pending": "قيد الانتظار",
    "Drag and drop files here or click to upload": "اسحب الملفات وأفلتها هنا أو انقر للتحميل",
    "Support images, videos, and folders": "دعم الصور ومقاطع الفيديو والمجلدات",
    "Search Media": "البحث في الوسائط",
    "Filter by name...": "تصفية حسب الاسم...",
    "New Folder / File": "مجلد / ملف جديد",
    "No media items found": "لم يتم العثور على عناصر وسائط",
    "items": "عناصر",
    "Visitor List": "قائمة الزوار",
    "Visitor Add": "إضافة زائر",
    "Visitor ID": "رقم الزائر",
    "To meet": "لمقابلة",
    "Add Visitor Information": "إضافة معلومات الزائر",
    "Visitor Details": "تفاصيل الزائر",
    "in": "في الداخل",
    "out": "في الخارج",
    "Name is required": "الاسم مطلوب"
  },
  bn: {
    "Language": "ভাষা",
    "Dashboard": "ড্যাশবোর্ড",
    "Student": "শিক্ষার্থী",
    "Parents": "অভিভাবক",
    "Teacher": "শিক্ষক",
    "User": "ব্যবহারকারী",
    "Attendance": "উপস্থিতি",
    "Student Attendance": "ছাত্র উপস্থিতি",
    "Teacher Attendance": "শিক্ষক উপস্থিতি",
    "User Attendance": "ব্যবহারকারী উপস্থিতি",
    "Message": "বার্তা",
    "Media": "মিডিয়া",
    "Leave Apply": "ছুটি আবেদন",
    "Announcement": "ঘোষণা",
    "Notice": "নোটিশ",
    "Event": "ইভেন্ট",
    "Holiday": "ছুটি",
    "Visitor Information": "দর্শনার্থীর তথ্য",
    "Report": "রিপোর্ট",
    "Library Books Report": "লাইব্রেরি বই রিপোর্ট",
    "Library Card Report": "লাইব্রেরি কার্ড রিপোর্ট",
    "Library Book Issue Report": "লাইব্রেরি বই প্রদান রিপোর্ট",
    "Member": "সদস্য",
    "Books": "বই",
    "Issue": "বই প্রদান",
    "Welcome to the Librarian Dashboard!": "লাইব্রেরিয়ান ড্যাশবোর্ডে আপনাকে স্বাগতম!",
    "Welcome to the Receptionist Dashboard!": "রিসেপশনিস্ট ড্যাশবোর্ডে আপনাকে স্বাগতম!",
    "Welcome to the Admin Dashboard!": "অ্যাডমিন ড্যাশবোর্ডে আপনাকে স্বাগতম!",
    "Welcome to the Dashboard!": "ড্যাশবোর্ডে আপনাকে স্বাগতম!",
    "Profile": "প্রোফাইল",
    "Password": "পাসওয়ার্ড",
    "Log out": "লগ আউট",
    "Username": "ব্যবহারকারীর নাম",
    "Email": "ইমেল",
    "Phone": "ফোন",
    "Address": "ঠিকানা",
    "Status": "অবস্থা",
    "Action": "অ্যাকশন",
    "Active": "সক্রিয়",
    "Sun": "রবি", "Mon": "সোম", "Tue": "মঙ্গল", "Wed": "বুধ", "Thu": "বৃহঃ", "Fri": "শুক্র", "Sat": "শনি",
    "January": "জানুয়ারী", "February": "ফেব্রুয়ারী", "March": "মার্চ", "April": "এপ্রিল", "May": "মে", "June": "জুন",
    "July": "জুলাই", "August": "আগস্ট", "September": "সেপ্টেম্বর", "October": "অক্টোবর", "November": "নভেম্বর", "December": "ডিসেম্বর",
    "today": "আজ", "month": "মাস", "week": "সপ্তাহ", "day": "দিন", "list": "তালিকা",

    "Library closed": "লাইব্রেরি বন্ধ",
    "The library will be closed tomorrow for system maintenance.": "সিস্টেম রক্ষণাবেক্ষণের জন্য আগামীকাল লাইব্রেরি বন্ধ থাকবে।",
    "Farewell Ceremony": "বিদায় অনুষ্ঠান",
    "The most of the words adopted by the Russian langu..": "রুশ ভাষা দ্বারা গৃহীত অধিকাংশ শব্দ..",
    "Second Semester Exam": "দ্বিতীয় সেমিস্টার পরীক্ষা",
    "Dedicated athlete, an amateur player, or a sport g..": "ডেডিকেটেড ক্রীড়াবিদ, অপেশাদার খেলোয়াড় বা ক্রীড়াপ্রেমী..",
    "First Semester Exam": "প্রথম সেমিস্টার পরীক্ষা",
    "If you are a dedicated athlete, an amateur player,..": "আপনি যদি একজন ডেডিকেটেড ক্রীড়াবিদ বা অপেশাদার খেলোয়াড় হন..",
    "Annual Sports Day": "বার্ষিক ক্রীড়া দিবস",
    "You surely are familiar with the sport language. A..": "আপনি নিশ্চয়ই ক্রীড়া ভাষার সাথে পরিচিত। আ..",
    "Teachers Reunion": "শিক্ষক পুনর্মিলনী",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "একজন অপেশাদার খেলোয়াড় বা ক্রীড়াপ্রেমী, আপনি অবশ্যই পরিচিত..",
    
    "librarian": "লাইব্রেরিয়ান",
    "receptionist": "রিসেপশনিস্ট",
    "Librarian": "লাইব্রেরিয়ান",
    "Receptionist": "রিসেপশনিস্ট",
    "Admin": "অ্যাডমিন",
    "Teacher Role": "শিক্ষক",
    "Student Role": "শিক্ষার্থী",
    "Parent Role": "অভিভাবক",
    "Accountant Role": "অ্যাকাউন্ট্যান্ট",
    "Fee Collection": "ফি সংগ্রহ",
    "My Child": "আমার সন্তান",
    "Child Attendance": "সন্তানের উপস্থিতি",
    "My Attendance": "আমার উপস্থিতি",
    "Subject": "বিষয়",
    "is successfully logged in. This section is currently under development.": "সফলভাবে লগইন করেছেন। এই বিভাগটি বর্তমানে উন্নয়নাধীন রয়েছে।",
    "All Students": "সব শিক্ষার্থী",
    "Copy": "কপি",
    "Excel": "এক্সেল",
    "CSV": "সিএসভি",
    "PDF": "পিডিএফ",
    "Select Class": "শ্রেণী নির্বাচন করুন",
    "Photo": "ছবি",
    "Roll": "রোল",
    "No data available in table": "তালিকায় কোনো তথ্য নেই",
    "Showing": "দেখাচ্ছে",
    "to": "থেকে",
    "of": "এর",
    "entries": "এন্ট্রি",
    "Previous": "পূর্ববর্তী",
    "Next": "পরবর্তী",
    "Arabic": "আরবি",
    "Bengali": "বাংলা",
    "Chinese": "চীনা",
    "English": "ইংরেজি",
    "French": "ফরাসি",
    "German": "জার্মান",
    "All Teachers": "সব শিক্ষক",
    "All Parents": "সব অভিভাবক",
    "All Users": "সব ব্যবহারকারী",
    "Designation": "পদবী",
    "Moderator": "মডারেটর",
    "Attendance Date": "উপস্থিতির তারিখ",
    "Present": "উপস্থিত",
    "Absent": "অনুপস্থিত",
    "Late": "বিলম্ব",
    "Father's Name": "পিতার নাম",
    "Mother's Name": "মাতার নাম",
    "Father's Profession": "পিতার পেশা",
    "Mother's Profession": "মাতার পেশা",
    "Class": "শ্রেণী",
    "Section": "শাখা",
    "Department": "বিভাগ",
    "Join Date": "যোগদানের তারিখ",
    "Role": "ভূমিকা",
    "Instructor": "ইন্সট্রাক্টর",
    "Female": "মহিলা",
    "Compose": "লিখুন",
    "Folders": "ফোল্ডার",
    "Drafts": "খসড়া",
    "Sent": "পাঠানো হয়েছে",
    "Trash": "আবর্জনা",
    "records per page": "প্রতি পৃষ্ঠায় রেকর্ড",
    "Add a leave application": "ছুটির আবেদন যোগ করুন",
    "Application To": "আবেদন প্রাপক",
    "Days": "দিন",
    "Attachment": "সংযুক্তি",
    "Schedule": "সময়সূচী",
    "Approved": "অনুমোদিত",
    "Pending": "পেন্ডিং",
    "Drag and drop files here or click to upload": "ফাইল ড্র্যাগ অ্যান্ড ড্রপ করুন অথবা আপলোড করতে ক্লিক করুন",
    "Support images, videos, and folders": "ছবি, ভিডিও এবং ফোল্ডার সমর্থন করে",
    "Search Media": "মিডিয়া খুঁজুন",
    "Filter by name...": "নাম দিয়ে ফিল্টার করুন...",
    "New Folder / File": "নতুন ফোল্ডার / ফাইল",
    "No media items found": "কোন মিডিয়া ফাইল পাওয়া যায়নি",
    "items": "আইটেম",
    "Visitor List": "দর্শনার্থী তালিকা",
    "Visitor Add": "দর্শনার্থী যুক্ত করুন",
    "Visitor ID": "দর্শনার্থী আইডি",
    "To meet": "সাক্ষাৎ করতে",
    "Add Visitor Information": "দর্শনার্থীর তথ্য যুক্ত করুন",
    "Visitor Details": "দর্শনার্থীর বিবরণ",
    "in": "ভিতরে",
    "out": "বাইরে",
    "Name is required": "নাম প্রয়োজন"
  },
  zh: {
    "Language": "语言",
    "Dashboard": "仪表板",
    "Student": "学生",
    "Parents": "家长",
    "Teacher": "教师",
    "User": "用户",
    "Attendance": "考勤",
    "Student Attendance": "学生考勤",
    "Teacher Attendance": "教师考勤",
    "User Attendance": "用户考勤",
    "Message": "消息",
    "Media": "媒体",
    "Leave Apply": "请假申请",
    "Announcement": "公告",
    "Notice": "通知",
    "Event": "活动",
    "Holiday": "节日",
    "Visitor Information": "访客信息",
    "Report": "报表",
    "Library Books Report": "图书报表",
    "Library Card Report": "图书卡报表",
    "Library Book Issue Report": "借阅报表",
    "Member": "成员",
    "Books": "图书",
    "Issue": "借出",
    "Welcome to the Librarian Dashboard!": "欢迎来到图书管理员仪表板！",
    "Welcome to the Receptionist Dashboard!": "欢迎来到接待员仪表板！",
    "Welcome to the Admin Dashboard!": "欢迎来到管理员仪表板！",
    "Welcome to the Dashboard!": "欢迎来到仪表板！",
    "Profile": "个人资料",
    "Password": "密码",
    "Log out": "登出",
    "Username": "用户名",
    "Email": "电子邮件",
    "Phone": "电话",
    "Address": "地址",
    "Status": "状态",
    "Action": "操作",
    "Active": "活跃",
    "Sun": "日", "Mon": "一", "Tue": "二", "Wed": "三", "Thu": "四", "Fri": "五", "Sat": "六",
    "January": "一月", "February": "二月", "March": "三月", "April": "四月", "May": "五月", "June": "六月",
    "July": "七月", "August": "八月", "September": "九月", "October": "十月", "November": "十一月", "December": "十二月",
    "today": "今天", "month": "月", "week": "周", "day": "日", "list": "列表",

    "Library closed": "图书馆关闭",
    "The library will be closed tomorrow for system maintenance.": "图书馆明天因系统维护关闭。",
    "Farewell Ceremony": "告别仪式",
    "The most of the words adopted by the Russian langu..": "俄语中吸收的大部分词汇..",
    "Second Semester Exam": "第二学期考试",
    "Dedicated athlete, an amateur player, or a sport g..": "专注的运动员、业余选手或运动爱好者..",
    "First Semester Exam": "第一学期考试",
    "If you are a dedicated athlete, an amateur player,..": "如果您是专注的运动员、业余选手..",
    "Annual Sports Day": "年度运动会",
    "You surely are familiar with the sport language. A..": "你肯定熟悉体育语言。A..",
    "Teachers Reunion": "教师重聚",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "业余选手或运动爱好者，您肯定熟悉..",
    
    "librarian": "图书管理员",
    "receptionist": "接待员",
    "Librarian": "图书管理员",
    "Receptionist": "接待员",
    "Admin": "管理员",
    "Teacher Role": "教师",
    "Student Role": "学生",
    "Parent Role": "家长",
    "Accountant Role": "会计",
    "Fee Collection": "费用收取",
    "My Child": "我的孩子",
    "Child Attendance": "孩子考勤",
    "My Attendance": "我的考勤",
    "Subject": "科目",
    "is successfully logged in. This section is currently under development.": "已成功登录。此部分目前正在开发中。",
    "All Students": "所有学生",
    "Copy": "复制",
    "Excel": "Excel",
    "CSV": "CSV",
    "PDF": "PDF",
    "Select Class": "选择班级",
    "Photo": "照片",
    "Roll": "学号",
    "No data available in table": "表中无可用数据",
    "Showing": "显示",
    "to": "至",
    "of": "的",
    "entries": "条条目",
    "Previous": "上一页",
    "Next": "下一页",
    "Arabic": "阿拉伯语",
    "Bengali": "孟加拉语",
    "Chinese": "中文",
    "English": "英语",
    "French": "法语",
    "German": "德语",
    "All Teachers": "所有教师",
    "All Parents": "所有家长",
    "All Users": "所有用户",
    "Designation": "职称",
    "Moderator": "版主",
    "Attendance Date": "考勤日期",
    "Present": "出勤",
    "Absent": "缺勤",
    "Late": "迟到",
    "Father's Name": "父亲姓名",
    "Mother's Name": "母亲姓名",
    "Father's Profession": "父亲职业",
    "Mother's Profession": "母亲职业",
    "Class": "班级",
    "Section": "小组",
    "Department": "部门",
    "Join Date": "加入日期",
    "Role": "角色",
    "Instructor": "讲师",
    "Female": "女",
    "Compose": "撰写",
    "Folders": "文件夹",
    "Drafts": "草稿",
    "Sent": "已发送",
    "Trash": "垃圾箱",
    "records per page": "每页记录",
    "Add a leave application": "添加请假申请",
    "Application To": "申请提交给",
    "Days": "天",
    "Attachment": "附件",
    "Schedule": "日程表",
    "Approved": "已批准",
    "Pending": "待定",
    "Drag and drop files here or click to upload": "拖放文件至此或点击上传",
    "Support images, videos, and folders": "支持图片、视频和文件夹",
    "Search Media": "搜索媒体",
    "Filter by name...": "按名称筛选...",
    "New Folder / File": "新建文件夹/文件",
    "No media items found": "未找到媒体项目",
    "items": "项目",
    "Visitor List": "访客列表",
    "Visitor Add": "添加访客",
    "Visitor ID": "访客ID",
    "To meet": "拜访对象",
    "Add Visitor Information": "添加访客信息",
    "Visitor Details": "访客详情",
    "in": "进入",
    "out": "离开",
    "Name is required": "姓名是必填项"
  },
  fr: {
    "Language": "Langue",
    "Dashboard": "Tableau de bord",
    "Student": "Étudiant",
    "Parents": "Parents",
    "Teacher": "Enseignant",
    "User": "Utilisateur",
    "Attendance": "Présence",
    "Student Attendance": "Présence des étudiants",
    "Teacher Attendance": "Présence des enseignants",
    "User Attendance": "Présence des utilisateurs",
    "Message": "Message",
    "Media": "Médias",
    "Leave Apply": "Demande de congé",
    "Announcement": "Annonce",
    "Notice": "Avis",
    "Event": "Événement",
    "Holiday": "Vacances",
    "Visitor Information": "Informations visiteurs",
    "Report": "Rapport",
    "Library Books Report": "Rapport de livres de bibliothèque",
    "Library Card Report": "Rapport de cartes de bibliothèque",
    "Library Book Issue Report": "Rapport de livres empruntés",
    "Member": "Membre",
    "Books": "Livres",
    "Issue": "Emprunts",
    "Welcome to the Librarian Dashboard!": "Bienvenue sur le tableau de bord du bibliothécaire !",
    "Welcome to the Receptionist Dashboard!": "Bienvenue sur le tableau de bord du réceptionniste !",
    "Welcome to the Admin Dashboard!": "Bienvenue sur le tableau de bord administrateur !",
    "Welcome to the Dashboard!": "Bienvenue sur le tableau de bord !",
    "Profile": "Profil",
    "Password": "Mot de passe",
    "Log out": "Se déconnecter",
    "Username": "Nom d'utilisateur",
    "Email": "E-mail",
    "Phone": "Téléphone",
    "Address": "Adresse",
    "Status": "Statut",
    "Action": "Action",
    "Active": "Actif",
    "Sun": "Dim", "Mon": "Lun", "Tue": "Mar", "Wed": "Mer", "Thu": "Jeu", "Fri": "Ven", "Sat": "Sam",
    "January": "Janvier", "February": "Février", "March": "Mars", "April": "Avril", "May": "Mai", "June": "Juin",
    "July": "Juillet", "August": "Août", "September": "Septembre", "October": "Octobre", "November": "Novembre", "December": "Décembre",
    "today": "aujourd'hui", "month": "mois", "week": "semaine", "day": "jour", "list": "liste",

    "Library closed": "Bibliothèque fermée",
    "The library will be closed tomorrow for system maintenance.": "La bibliothèque sera fermée demain pour maintenance du système.",
    "Farewell Ceremony": "Cérémonie d'adieu",
    "The most of the words adopted by the Russian langu..": "La plupart des mots adoptés par la langue russe..",
    "Second Semester Exam": "Examen du deuxième semestre",
    "Dedicated athlete, an amateur player, or a sport g..": "Athlète dévoué, joueur amateur ou passionné de sport..",
    "First Semester Exam": "Examen du premier semestre",
    "If you are a dedicated athlete, an amateur player,..": "Si vous êtes un athlète dévoué, un joueur amateur..",
    "Annual Sports Day": "Journée sportive annuelle",
    "You surely are familiar with the sport language. A..": "Vous connaissez sûrement le langage du sport. A..",
    "Teachers Reunion": "Réunion des enseignants",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "Un joueur amateur ou un passionné de sport, vous connaissez sûrement..",
    
    "librarian": "bibliothécaire",
    "receptionist": "réceptionniste",
    "Librarian": "Bibliothécaire",
    "Receptionist": "Réceptionniste",
    "Admin": "Administrateur",
    "Teacher Role": "Enseignant",
    "Student Role": "Étudiant",
    "Parent Role": "Parent",
    "Accountant Role": "Comptable",
    "Fee Collection": "Collecte des frais",
    "My Child": "Mon enfant",
    "Child Attendance": "Présence de l'enfant",
    "My Attendance": "Ma présence",
    "Subject": "Matière",
    "is successfully logged in. This section is currently under development.": "est connecté avec succès. Cette section est actuellement en cours de développement.",
    "All Students": "Tous les étudiants",
    "Copy": "Copier",
    "Excel": "Excel",
    "CSV": "CSV",
    "PDF": "PDF",
    "Select Class": "Sélectionner une classe",
    "Photo": "Photo",
    "Roll": "Numéro",
    "No data available in table": "Aucune donnée disponible dans le tableau",
    "Showing": "Affichage de",
    "to": "à",
    "of": "sur",
    "entries": "entrées",
    "Previous": "Précédent",
    "Next": "Suivant",
    "Arabic": "Arabe",
    "Bengali": "Bengali",
    "Chinese": "Chinois",
    "English": "Anglais",
    "French": "Français",
    "German": "Allemand",
    "All Teachers": "Tous les enseignants",
    "All Parents": "Tous les parents",
    "All Users": "Tous les utilisateurs",
    "Designation": "Désignation",
    "Moderator": "Modérateur",
    "Attendance Date": "Date de présence",
    "Present": "Présent",
    "Absent": "Absent",
    "Late": "En retard",
    "Father's Name": "Nom du père",
    "Mother's Name": "Nom de la mère",
    "Father's Profession": "Profession du père",
    "Mother's Profession": "Profession de la mère",
    "Class": "Classe",
    "Section": "Section",
    "Department": "Département",
    "Join Date": "Date d'adhésion",
    "Role": "Rôle",
    "Instructor": "Instructeur",
    "Female": "Femme",
    "Compose": "Rédiger",
    "Folders": "Dossiers",
    "Drafts": "Brouillons",
    "Sent": "Envoyé",
    "Trash": "Corbeille",
    "records per page": "enregistrements par page",
    "Add a leave application": "Ajouter une demande de congé",
    "Application To": "Demande à",
    "Days": "Jours",
    "Attachment": "Pièce jointe",
    "Schedule": "Horaire",
    "Approved": "Approuvé",
    "Pending": "En attente",
    "Drag and drop files here or click to upload": "Glissez et déposez des fichiers ici ou cliquez pour télécharger",
    "Support images, videos, and folders": "Prend en charge les images, vidéos et dossiers",
    "Search Media": "Rechercher un média",
    "Filter by name...": "Filtrer par nom...",
    "New Folder / File": "Nouveau dossier / fichier",
    "No media items found": "Aucun élément multimédia trouvé",
    "items": "éléments",
    "Visitor List": "Liste des visiteurs",
    "Visitor Add": "Ajouter un visiteur",
    "Visitor ID": "ID du visiteur",
    "To meet": "Pour rencontrer",
    "Add Visitor Information": "Ajouter des informations sur le visiteur",
    "Visitor Details": "Détails du visiteur",
    "in": "Entré",
    "out": "Sorti",
    "Name is required": "Le nom est requis"
  },
  de: {
    "Language": "Sprache",
    "Dashboard": "Dashboard",
    "Student": "Schüler",
    "Parents": "Eltern",
    "Teacher": "Lehrer",
    "User": "Benutzer",
    "Attendance": "Anwesenheit",
    "Student Attendance": "Schüleranwesenheit",
    "Teacher Attendance": "Lehreranwesenheit",
    "User Attendance": "Benutzeranwesenheit",
    "Message": "Nachricht",
    "Media": "Medien",
    "Leave Apply": "Urlaub beantragen",
    "Announcement": "Ankündigung",
    "Notice": "Bekanntmachung",
    "Event": "Veranstaltung",
    "Holiday": "Feiertag",
    "Visitor Information": "Besucherinformationen",
    "Report": "Bericht",
    "Library Books Report": "Bibliotheksbücherbericht",
    "Library Card Report": "Bibliothekskartenbericht",
    "Library Book Issue Report": "Buchausgabebericht",
    "Member": "Mitglied",
    "Books": "Bücher",
    "Issue": "Ausgabe",
    "Welcome to the Librarian Dashboard!": "Willkommen im Bibliothekar-Dashboard!",
    "Welcome to the Receptionist Dashboard!": "Willkommen im Empfangs-Dashboard!",
    "Welcome to the Admin Dashboard!": "Willkommen im Admin-Dashboard!",
    "Welcome to the Dashboard!": "Willkommen im Dashboard!",
    "Profile": "Profil",
    "Password": "Passwort",
    "Log out": "Abmelden",
    "Username": "Benutzername",
    "Email": "E-Mail",
    "Phone": "Telefon",
    "Address": "Adresse",
    "Status": "Status",
    "Action": "Aktion",
    "Active": "Aktiv",
    "Sun": "So", "Mon": "Mo", "Tue": "Di", "Wed": "Mi", "Thu": "Do", "Fri": "Fr", "Sat": "Sa",
    "January": "Januar", "February": "Februar", "March": "März", "April": "April", "May": "Mai", "June": "Juni",
    "July": "Juli", "August": "August", "September": "September", "October": "Oktober", "November": "November", "December": "Dezember",
    "today": "Heute", "month": "Monat", "week": "Woche", "day": "Tag", "list": "Liste",

    "Library closed": "Bibliothek geschlossen",
    "The library will be closed tomorrow for system maintenance.": "Die Bibliothek bleibt morgen wegen Systemwartung geschlossen.",
    "Farewell Ceremony": "Abschiedsfeier",
    "The most of the words adopted by the Russian langu..": "Die meisten aus der russischen Sprache übernommenen Wörter..",
    "Second Semester Exam": "Prüfung für das zweite Semester",
    "Dedicated athlete, an amateur player, or a sport g..": "Engagierter Athlet, Amateurspieler oder Sportbegeisterter..",
    "First Semester Exam": "Prüfung für das erste Semester",
    "If you are a dedicated athlete, an amateur player,..": "Wenn Sie ein engagierter Athlet oder Amateurspieler sind..",
    "Annual Sports Day": "Jährlicher Sporttag",
    "You surely are familiar with the sport language. A..": "Sie sind sicherlich mit der Sportsprache vertraut. A..",
    "Teachers Reunion": "Lehrertreffen",
    "An amateur player, or a sport geek, than you surely are familiar with ..": "Ein Amateurspieler oder Sportbegeisterter, dann sind Sie sicherlich vertraut..",
    
    "librarian": "bibliothekar",
    "receptionist": "empfang",
    "Librarian": "Bibliothekar",
    "Receptionist": "Empfangsmitarbeiter",
    "Admin": "Admin",
    "Teacher Role": "Lehrer",
    "Student Role": "Schüler",
    "Parent Role": "Elternteil",
    "Accountant Role": "Buchhalter",
    "Fee Collection": "Gebührenerhebung",
    "My Child": "Mein Kind",
    "Child Attendance": "Kinderanwesenheit",
    "My Attendance": "Meine Anwesenheit",
    "Subject": "Fach",
    "is successfully logged in. This section is currently under development.": "hat sich erfolgreich angemeldet. Dieser Bereich befindet sich derzeit in der Entwicklung.",
    "All Students": "Alle Schüler",
    "Copy": "Kopieren",
    "Excel": "Excel",
    "CSV": "CSV",
    "PDF": "PDF",
    "Select Class": "Klasse auswählen",
    "Photo": "Foto",
    "Roll": "Rollnummer",
    "No data available in table": "Keine Daten im Tabellenbereich verfügbar",
    "Showing": "Zeige",
    "to": "bis",
    "of": "von",
    "entries": "Einträgen",
    "Previous": "Zurück",
    "Next": "Weiter",
    "Arabic": "Arabisch",
    "Bengali": "Bengalisch",
    "Chinese": "Chinesisch",
    "English": "Englisch",
    "French": "Französisch",
    "German": "Deutsch",
    "All Teachers": "Alle Lehrer",
    "All Parents": "Alle Eltern",
    "All Users": "Alle Benutzer",
    "Designation": "Bezeichnung",
    "Moderator": "Moderator",
    "Attendance Date": "Anwesenheitsdatum",
    "Present": "Anwesend",
    "Absent": "Abwesend",
    "Late": "Verspätet",
    "Father's Name": "Vatername",
    "Mother's Name": "Muttername",
    "Father's Profession": "Beruf des Vaters",
    "Mother's Profession": "Beruf der Mutter",
    "Class": "Klasse",
    "Section": "Bereich",
    "Department": "Abteilung",
    "Join Date": "Beitrittsdatum",
    "Role": "Rolle",
    "Instructor": "Ausbilder",
    "Female": "Weiblich",
    "Compose": "Verfassen",
    "Folders": "Ordner",
    "Drafts": "Entwürfe",
    "Sent": "Gesendet",
    "Trash": "Papierkorb",
    "records per page": "Einträge pro Seite",
    "Add a leave application": "Urlaubsantrag hinzufügen",
    "Application To": "Antrag an",
    "Days": "Tage",
    "Attachment": "Anhang",
    "Schedule": "Zeitplan",
    "Approved": "Genehmigt",
    "Pending": "Ausstehend",
    "Drag and drop files here or click to upload": "Dateien hierher ziehen und ablegen oder zum Hochladen klicken",
    "Support images, videos, and folders": "Unterstützt Bilder, Videos und Ordner",
    "Search Media": "Medien durchsuchen",
    "Filter by name...": "Nach Name filtern...",
    "New Folder / File": "Neuer Ordner / Datei",
    "No media items found": "Keine Medienelemente gefunden",
    "items": "Elemente",
    "Visitor List": "Besucherliste",
    "Visitor Add": "Besucher hinzufügen",
    "Visitor ID": "Besucher-ID",
    "To meet": "Zu treffen",
    "Add Visitor Information": "Besucherinformationen hinzufügen",
    "Visitor Details": "Besucherdetails",
    "in": "Anwesend",
    "out": "Abwesend",
    "Name is required": "Name ist erforderlich"
  }
};

interface LanguageContextType {
  language: string;
  changeLanguage: (code: string) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [langCode, setLangCode] = useState<string>(() => {
    return localStorage.getItem("appLanguage") || "en";
  });

  const changeLanguage = (code: string) => {
    if (TRANSLATIONS[code]) {
      setLangCode(code);
      localStorage.setItem("appLanguage", code);
    }
  };

  const t = (key: string): string => {
    if (!key) return "";
    
    const trimmedKey = key.trim();
    if (TRANSLATIONS[langCode]?.[trimmedKey]) {
      return TRANSLATIONS[langCode][trimmedKey];
    }
    
    // Dynamic matching for welcome greetings
    if (trimmedKey.startsWith("Welcome to the ") && trimmedKey.endsWith(" Dashboard!")) {
      const role = trimmedKey.replace("Welcome to the ", "").replace(" Dashboard!", "");
      const welcomePrefix = langCode === "ar" ? "مرحبًا بك في لوحة تحكم " :
                            langCode === "bn" ? "ড্যাশবোর্ডে আপনাকে স্বাগতম!" :
                            langCode === "zh" ? "欢迎来到" :
                            langCode === "fr" ? "Bienvenue sur le tableau de bord du " :
                            langCode === "de" ? "Willkommen im " : "Welcome to the ";
      
      const welcomeSuffix = langCode === "ar" ? "!" :
                            langCode === "bn" ? "" :
                            langCode === "zh" ? "仪表板！" :
                            langCode === "fr" ? " !" :
                            langCode === "de" ? "-Dashboard!" : " Dashboard!";

      const translatedRole = TRANSLATIONS[langCode]?.[role] || role;
      
      if (langCode === "bn") {
        return `${translatedRole} ${welcomePrefix}`;
      }
      return `${welcomePrefix}${translatedRole}${welcomeSuffix}`;
    }

    if (trimmedKey.includes("successfully logged in. This section is currently under development.")) {
      // Find the name
      const nameMatch = trimmedKey.match(/^Hello\s+(.*?),\s+you\s+are/);
      const name = nameMatch ? nameMatch[1] : "User";
      
      if (langCode === "ar") {
        return `مرحبًا ${name}، تم تسجيل دخولك بنجاح. هذا القسم قيد التطوير حاليًا.`;
      }
      if (langCode === "bn") {
        return `হ্যালো ${name}, আপনি সফলভাবে লগইন করেছেন। এই বিভাগটি বর্তমানে উন্নয়নাধীন রয়েছে।`;
      }
      if (langCode === "zh") {
        return `您好 ${name}，您已成功登录。此部分目前正在开发中。`;
      }
      if (langCode === "fr") {
        return `Bonjour ${name}, vous êtes connecté avec succès. Cette section est actuellement en cours de développement.`;
      }
      if (langCode === "de") {
        return `Hallo ${name}, Sie haben sich erfolgreich angemeldet. Dieser Bereich befindet sich derzeit in der Entwicklung.`;
      }
      return `Hello ${name}, you are successfully logged in. This section is currently under development.`;
    }

    return TRANSLATIONS["en"]?.[trimmedKey] || key;
  };

  const currentLanguage = LANGUAGES.find((l) => l.code === langCode) || LANGUAGES[3];

  return (
    <LanguageContext.Provider value={{ language: langCode, changeLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
