import express from "express";
import authRoutes from "./authRoutes.js";
import studentRoutes from "./studentRoutes.js";
import teacherRoutes from "./teacherRoutes.js";
import parentRoutes from "./parentRoutes.js";
import userRoutes from "./userRoutes.js";
import visitorRoutes from "./visitorRoutes.js";
import noticeRoutes from "./noticeRoutes.js";
import eventRoutes from "./eventRoutes.js";
import holidayRoutes from "./holidayRoutes.js";
import leaveRoutes from "./leaveRoutes.js";
import documentRoutes from "./documentRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";

import enquiryRoutes from "./enquiryRoutes.js";
import importRoutes from "./importRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import attendanceRoutes from "./attendanceRoutes.js";

import messageSettingRoutes from "./messageSettingRoutes.js";
import classRoutes from "./classRoutes.js";
import sectionRoutes from "./sectionRoutes.js";
import subjectRoutes from "./subjectRoutes.js";
import syllabusRoutes from "./syllabusRoutes.js";
import assignmentRoutes from "./assignmentRoutes.js";
import routineRoutes from "./routineRoutes.js";
import examRoutes from "./examRoutes.js";
import examScheduleRoutes from "./examScheduleRoutes.js";
import gradeRoutes from "./gradeRoutes.js";
import examAttendanceRoutes from "./examAttendanceRoutes.js";
import markRoutes from "./markRoutes.js";
import markDistributionRoutes from "./markDistributionRoutes.js";
import promotionRoutes from "./promotionRoutes.js";
import mailSmsRoutes from "./mailSmsRoutes.js";
import questionGroupRoutes from "./questionGroupRoutes.js";
import questionLevelRoutes from "./questionLevelRoutes.js";
import questionBankRoutes from "./questionBankRoutes.js";
import onlineExamRoutes from "./onlineExamRoutes.js";
import instructionRoutes from "./instructionRoutes.js";
import takeExamRoutes from "./takeExamRoutes.js";
import salaryTemplateRoutes from "./salaryTemplateRoutes.js";
import hourlyTemplateRoutes from "./hourlyTemplateRoutes.js";
import overtimeRoutes from "./overtimeRoutes.js";
import schoolSettingRoutes from "./schoolSettingRoutes.js";
import rolePermissionRoutes from "./rolePermissionRoutes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/parents", parentRoutes);
router.use("/users", userRoutes);
router.use("/visitors", visitorRoutes);
router.use("/notices", noticeRoutes);
router.use("/events", eventRoutes);
router.use("/holidays", holidayRoutes);
router.use("/leaves", leaveRoutes);
router.use("/documents", documentRoutes);
router.use("/dashboard", dashboardRoutes);

router.use("/enquiries", enquiryRoutes);
router.use("/import", importRoutes);
router.use("/upload", uploadRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/message-settings", messageSettingRoutes);
router.use("/school-settings", schoolSettingRoutes);
router.use("/role-permissions", rolePermissionRoutes);
router.use("/classes", classRoutes);
router.use("/sections", sectionRoutes);
router.use("/subjects", subjectRoutes);
router.use("/syllabuses", syllabusRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/routines", routineRoutes);
router.use("/exams", examRoutes);
router.use("/exam-schedules", examScheduleRoutes);
router.use("/grades", gradeRoutes);
router.use("/exam-attendances", examAttendanceRoutes);
router.use("/marks", markRoutes);
router.use("/mark-distributions", markDistributionRoutes);
router.use("/promotions", promotionRoutes);
router.use("/mail-sms", mailSmsRoutes);
router.use("/question-groups", questionGroupRoutes);
router.use("/question-levels", questionLevelRoutes);
router.use("/question-banks", questionBankRoutes);
router.use("/online-exams", onlineExamRoutes);
router.use("/instructions", instructionRoutes);
router.use("/take-exams", takeExamRoutes);
router.use("/salary-templates", salaryTemplateRoutes);
router.use("/hourly-templates", hourlyTemplateRoutes);
router.use("/overtimes", overtimeRoutes);

export default router;
