import type { SidebarEntry } from "./LibrariandashboardData";

export const sidebarMenuItems: SidebarEntry[] = [
  { type: "link", data: { icon: "fa-laptop", label: "Dashboard", href: "/dashboard", isActive: true } },
  { type: "link", data: { icon: "fa-user", label: "Student", href: "/dashboard/student" } },
  { type: "link", data: { icon: "fa-user", label: "Parents", href: "/dashboard/parents" } },
  { type: "link", data: { icon: "fa-users", label: "Staff", href: "/dashboard/staff" } },
  {
    type: "treeview",
    data: {
      icon: "fa-graduation-cap",
      label: "Academic",
      defaultOpen: false,
      children: [
        { icon: "fa-building", label: "Class", href: "/dashboard/academic/class" },
        { icon: "fa-columns", label: "Section", href: "/dashboard/academic/section" },
        { icon: "fa-book", label: "Subject", href: "/dashboard/academic/subject" },
        { icon: "fa-file-text", label: "Syllabus", href: "/dashboard/academic/syllabus" },
        { icon: "fa-tasks", label: "Assignments", href: "/dashboard/academic/assignments" },
        { icon: "fa-calendar", label: "Routine", href: "/dashboard/academic/routine" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-clock-o",
      label: "Attendance",
      defaultOpen: false,
      children: [
        { icon: "fa-user", label: "Student Attendance", href: "/dashboard/attendance/student" },
        { icon: "fa-user", label: "Teacher Attendance", href: "/dashboard/attendance/teacher" },
        { icon: "fa-users", label: "User Attendance", href: "/dashboard/attendance/user" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-pencil-square-o",
      label: "Exam",
      defaultOpen: false,
      children: [
        { icon: "fa-pencil", label: "Exam", href: "/dashboard/exam" },
        { icon: "fa-calendar", label: "Exam Schedule", href: "/dashboard/exam/schedule" },
        { icon: "fa-star", label: "Grade", href: "/dashboard/exam/grade" },
        { icon: "fa-check-square-o", label: "Exam Attendance", href: "/dashboard/exam/attendance" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-file-text-o",
      label: "Mark",
      defaultOpen: false,
      children: [
        { icon: "fa-file-text", label: "Mark", href: "/dashboard/mark" },
        { icon: "fa-pie-chart", label: "Mark Distribution", href: "/dashboard/mark/distribution" },
        { icon: "fa-line-chart", label: "Promotion", href: "/dashboard/mark/promotion" },
      ],
    },
  },
  { type: "link", data: { icon: "fa-envelope", label: "Message", href: "/dashboard/message" } },
  { type: "link", data: { icon: "fa-camera", label: "Media", href: "/dashboard/media" } },
  { type: "link", data: { icon: "fa-paper-plane", label: "Mail / SMS", href: "/dashboard/mail-sms" } },
  {
    type: "treeview",
    data: {
      icon: "fa-laptop",
      label: "Online Exam",
      defaultOpen: false,
      children: [
        { icon: "fa-folder", label: "Question Group", href: "/dashboard/online-exam/question-group" },
        { icon: "fa-signal", label: "Question Level", href: "/dashboard/online-exam/question-level" },
        { icon: "fa-database", label: "Question Bank", href: "/dashboard/online-exam/question-bank" },
        { icon: "fa-file-text", label: "Online Exam", href: "/dashboard/online-exam" },
        { icon: "fa-info-circle", label: "Instruction", href: "/dashboard/online-exam/instruction" },
        { icon: "fa-edit", label: "Take Exam", href: "/dashboard/online-exam/take-exam" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-money",
      label: "Payroll",
      defaultOpen: false,
      children: [
        { icon: "fa-file-text", label: "Salary Template", href: "/dashboard/payroll/salary-template" },
        { icon: "fa-clock-o", label: "Hourly Template", href: "/dashboard/payroll/hourly-template" },
        { icon: "fa-usd", label: "Manage Salary", href: "/dashboard/payroll/manage-salary" },
        { icon: "fa-credit-card", label: "Make Payments", href: "/dashboard/payroll/make-payment" },
        { icon: "fa-plus-circle", label: "Overtime", href: "/dashboard/payroll/overtime" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-cubes",
      label: "Asset Management",
      defaultOpen: false,
      children: [
        { icon: "fa-truck", label: "Vendor", href: "/dashboard/asset/vendor" },
        { icon: "fa-map-marker", label: "Location", href: "/dashboard/asset/location" },
        { icon: "fa-list", label: "Asset Category", href: "/dashboard/asset/category" },
        { icon: "fa-archive", label: "Asset", href: "/dashboard/asset" },
        { icon: "fa-check", label: "Asset Assignments", href: "/dashboard/asset/assignments" },
        { icon: "fa-shopping-cart", label: "Purchase", href: "/dashboard/asset/purchase" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-bar-chart",
      label: "Inventory",
      defaultOpen: false,
      children: [
        { icon: "fa-list", label: "Category", href: "/dashboard/inventory/category" },
        { icon: "fa-tag", label: "Product", href: "/dashboard/inventory/product" },
        { icon: "fa-building", label: "Warehouse", href: "/dashboard/inventory/warehouse" },
        { icon: "fa-handshake-o", label: "Supplier", href: "/dashboard/inventory/supplier" },
        { icon: "fa-shopping-cart", label: "Purchase", href: "/dashboard/inventory/purchase" },
        { icon: "fa-usd", label: "Sale", href: "/dashboard/inventory/sale" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-paper-plane",
      label: "Leave Application",
      defaultOpen: false,
      children: [
        { icon: "fa-list", label: "Leave Category", href: "/dashboard/leave/category" },
        { icon: "fa-user-plus", label: "Leave Assign", href: "/dashboard/leave/assign" },
        { icon: "fa-paper-plane", label: "Leave Apply", href: "/dashboard/leave-apply" },
        { icon: "fa-file-text", label: "Leave Application", href: "/dashboard/leave/application" },
      ],
    },
  },
  { type: "link", data: { icon: "fa-video-camera", label: "Tutorial", href: "/dashboard/tutorial" } },
  { type: "link", data: { icon: "fa-video-camera", label: "gmeetliveclass", href: "/dashboard/gmeetliveclass" } },
  {
    type: "treeview",
    data: {
      icon: "fa-child",
      label: "Child",
      defaultOpen: false,
      children: [
        { icon: "fa-list", label: "Activities Category", href: "/dashboard/child/activities-category" },
        { icon: "fa-gamepad", label: "Activities", href: "/dashboard/child/activities" },
        { icon: "fa-heart", label: "Child Care", href: "/dashboard/child/child-care" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-book",
      label: "Library",
      defaultOpen: false,
      children: [
        { icon: "fa-user", label: "Member", href: "/dashboard/library/member" },
        { icon: "fa-book", label: "Books", href: "/dashboard/library/books" },
        { icon: "fa-shopping-cart", label: "Issue", href: "/dashboard/library/issue" },
        { icon: "fa-tablet", label: "E-Books", href: "/dashboard/library/ebooks" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-bus",
      label: "Transport",
      defaultOpen: false,
      children: [
        { icon: "fa-bus", label: "Transport", href: "/dashboard/transport" },
        { icon: "fa-user", label: "Member", href: "/dashboard/transport/member" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-bed",
      label: "Hostel",
      defaultOpen: false,
      children: [
        { icon: "fa-building", label: "Hostel", href: "/dashboard/hostel" },
        { icon: "fa-list", label: "Category", href: "/dashboard/hostel/category" },
        { icon: "fa-user", label: "Member", href: "/dashboard/hostel/member" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-handshake-o",
      label: "Sponsorship",
      defaultOpen: false,
      children: [
        { icon: "fa-user", label: "Candidate", href: "/dashboard/sponsorship/candidate" },
        { icon: "fa-users", label: "Sponsor", href: "/dashboard/sponsorship/sponsor" },
        { icon: "fa-money", label: "Sponsorship", href: "/dashboard/sponsorship" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-calculator",
      label: "Account",
      defaultOpen: false,
      children: [
        { icon: "fa-list", label: "Fee Types", href: "/dashboard/account/fee-types" },
        { icon: "fa-file-text", label: "Invoice", href: "/dashboard/account/invoice" },
        { icon: "fa-history", label: "Payment History", href: "/dashboard/account/payment-history" },
        { icon: "fa-minus-circle", label: "Expense", href: "/dashboard/account/expense" },
        { icon: "fa-plus-circle", label: "Income", href: "/dashboard/account/income" },
        { icon: "fa-globe", label: "Global Payment", href: "/dashboard/account/global-payment" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-bullhorn",
      label: "Announcement",
      defaultOpen: false,
      children: [
        { icon: "fa-calendar", label: "Notice", href: "/dashboard/announcement/notice" },
        { icon: "fa-calendar-check-o", label: "Events", href: "/dashboard/announcement/event" },
        { icon: "fa-flag", label: "Holiday", href: "/dashboard/announcement/holiday" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-file-text",
      label: "Report",
      defaultOpen: false,
      children: [
        { icon: "fa-file-text", label: "Class Report", href: "/dashboard/report/class" },
        { icon: "fa-file-text", label: "Sponsorship Report", href: "/dashboard/report/sponsorship" },
        { icon: "fa-file-text", label: "Student Report", href: "/dashboard/report/student" },
        { icon: "fa-id-card", label: "ID Card Report", href: "/dashboard/report/id-card" },
        { icon: "fa-file-text", label: "Admit Card Report", href: "/dashboard/report/admit-card" },
        { icon: "fa-calendar", label: "Routine Report", href: "/dashboard/report/routine" },
        { icon: "fa-calendar", label: "Exam Schedule Report", href: "/dashboard/report/exam-schedule" },
        { icon: "fa-clock-o", label: "Attendance Report", href: "/dashboard/report/attendance" },
        { icon: "fa-clock-o", label: "Attendance Overview Report", href: "/dashboard/report/attendance-overview" },
        { icon: "fa-book", label: "Library Books Report", href: "/dashboard/report/library-books" },
        { icon: "fa-id-card", label: "Library Card Report", href: "/dashboard/report/library-card" },
        { icon: "fa-book", label: "Library Book Issue Report", href: "/dashboard/report/library-book-issue" },
        { icon: "fa-user", label: "Personal Report", href: "/dashboard/report/personal" },
        { icon: "fa-line-chart", label: "Mark Usage Report", href: "/dashboard/report/mark-usage" },
        { icon: "fa-file-text", label: "Tabulation Sheet Report", href: "/dashboard/report/tabulation-sheet" },
        { icon: "fa-file-text", label: "Mark Sheet Report", href: "/dashboard/report/mark-sheet" },
        { icon: "fa-vcard", label: "Progress Card Report", href: "/dashboard/report/progress-card" },
        { icon: "fa-users", label: "Teacher Gender Report", href: "/dashboard/report/teacher-gender" },
        { icon: "fa-laptop", label: "Online Exam Report", href: "/dashboard/report/online-exam" },
        { icon: "fa-question-circle", label: "Online Exam Question Report", href: "/dashboard/report/online-exam-question" },
        { icon: "fa-check-square-o", label: "Online Exam Question Answers Report", href: "/dashboard/report/online-exam-answers" },
        { icon: "fa-globe", label: "Online Admission Report", href: "/dashboard/report/online-admission" },
        { icon: "fa-certificate", label: "Certificate Report", href: "/dashboard/report/certificate" },
        { icon: "fa-paper-plane", label: "Leave Application Report", href: "/dashboard/report/leave-application" },
        { icon: "fa-shopping-cart", label: "Product Purchase Report", href: "/dashboard/report/product-purchase" },
        { icon: "fa-usd", label: "Product Sale Report", href: "/dashboard/report/product-sale" },
        { icon: "fa-money", label: "Academic Payment/Fees Report", href: "/dashboard/report/academic-payment" },
        { icon: "fa-money", label: "Fees Report", href: "/dashboard/report/fees" },
        { icon: "fa-money", label: "Due Fees Report", href: "/dashboard/report/due-fees" },
        { icon: "fa-money", label: "Balance Fees Report", href: "/dashboard/report/balance-fees" },
        { icon: "fa-history", label: "Transaction Report", href: "/dashboard/report/transaction" },
        { icon: "fa-exclamation-circle", label: "Students Fine Report", href: "/dashboard/report/students-fine" },
        { icon: "fa-pie-chart", label: "Overview Report", href: "/dashboard/report/overview" },
        { icon: "fa-money", label: "Salary Report", href: "/dashboard/report/salary" },
        { icon: "fa-book", label: "Account Ledger Report", href: "/dashboard/report/account-ledger" },
      ],
    },
  },
  { type: "link", data: { icon: "fa-globe", label: "Online Admission", href: "/dashboard/online-admission" } },
  {
    type: "treeview",
    data: {
      icon: "fa-cogs",
      label: "Administrator",
      defaultOpen: false,
      children: [
        { icon: "fa-calendar", label: "Academic Year", href: "/dashboard/administrator/academic-year" },
        { icon: "fa-users", label: "Student Group", href: "/dashboard/administrator/student-group" },
        { icon: "fa-exclamation-triangle", label: "Complaint", href: "/dashboard/administrator/complaint" },
        { icon: "fa-file-text", label: "Purchase Template", href: "/dashboard/administrator/purchase-template" },
        { icon: "fa-key", label: "Reset Admin", href: "/dashboard/administrator/reset-admin" },
        { icon: "fa-lock", label: "Passcode", href: "/dashboard/administrator/passcode" },
        { icon: "fa-user", label: "Make Login Templates", href: "/dashboard/administrator/make-login-templates" },
        { icon: "fa-upload", label: "Import", href: "/dashboard/administrator/import" },
        { icon: "fa-database", label: "Backup", href: "/dashboard/administrator/backup" },
        { icon: "fa-envelope", label: "Mail Log", href: "/dashboard/administrator/mail-log" },
        { icon: "fa-sign-out", label: "Auto Logout", href: "/dashboard/administrator/auto-logout" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-desktop",
      label: "Frontend",
      defaultOpen: false,
      children: [
        { icon: "fa-comments", label: "Visitor Comments", href: "/dashboard/frontend/visitor-comments" },
        { icon: "fa-edit", label: "Take Exam", href: "/dashboard/frontend/take-exam" },
        { icon: "fa-file", label: "Pages", href: "/dashboard/frontend/pages" },
        { icon: "fa-book", label: "Library", href: "/dashboard/frontend/library" },
      ],
    },
  },
  {
    type: "treeview",
    data: {
      icon: "fa-sliders",
      label: "Settings",
      defaultOpen: false,
      children: [
        { icon: "fa-university", label: "School Settings", href: "/dashboard/settings/school" },
        { icon: "fa-users", label: "Users & Permission", href: "/dashboard/settings/users-permission" },
        { icon: "fa-envelope", label: "Message & Mail", href: "/dashboard/settings/message-mail" },
        { icon: "fa-certificate", label: "Product License", href: "/dashboard/settings/product-license" },
        { icon: "fa-cog", label: "General Setting", href: "/dashboard/settings/general" },
        { icon: "fa-usd", label: "Financial Settings", href: "/dashboard/settings/financial" },
        { icon: "fa-credit-card", label: "Payment Settings", href: "/dashboard/settings/payment" },
        { icon: "fa-mobile", label: "SMS Settings", href: "/dashboard/settings/sms" },
        { icon: "fa-envelope", label: "Email Setting", href: "/dashboard/settings/email" },
      ],
    },
  },
  { type: "link", data: { icon: "fa-list", label: "Current Enquiries", href: "/dashboard/enquiry/current" } },
];
